"""add user category preferences

Revision ID: 506b89151b6f
Revises: d1a9f3c72b8e
Create Date: 2026-06-07 20:36:35.526952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '506b89151b6f'
down_revision: Union[str, None] = 'd1a9f3c72b8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usercategorypreference',
    sa.Column('user_username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_username'], ['user.username'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usercategorypreference')
    # ### end Alembic commands ###
